name: Telegram News Bot 2b

on:
  schedule:
    - cron: '0 * * * *'  # запуск каждый час
  workflow_dispatch:      # ручной запуск из интерфейса GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHANNELS: ${{ secrets.CHANNELS }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: python main.py

      - name: Commit updated processed_links_json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull
          git add processed_links.json rejected_news.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update processed and rejected links"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          fi
